language: php

php:
 - 5.5
 - 5.6
 - hvvm

services:
  - mysql

before_script:
  - composer install --dev --prefer-source --no-interaction
  - mysql -e 'create database testing;'

script:
  - vendor/bin/phpspec run
  - vendor/bin/phpunit